name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  mix:
    name: mix compile (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.x
            otp: 23.x
          - elixir: 1.13.x
            otp: 24.x
          - elixir: 1.13.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 23.x
          - elixir: 1.14.x
            otp: 24.x
          - elixir: 1.14.x
            otp: 25.x
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile
      - run: mix format --check-formatted

  mix_windows:
    name: mix test windows (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.x
            otp: 23.x
          - elixir: 1.13.x
            otp: 24.x
          - elixir: 1.13.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 23.x
          - elixir: 1.14.x
            otp: 24.x
          - elixir: 1.14.x
            otp: 25.x
    env:
      MIX_ENV: test
    steps:
      - name: Set git to use original line ending
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile
